---
title: "Proyecto_17ab"
author: "Irene Pérez"
date: "2026-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




Carga de los datos obtenidos mediante el fichero 

```{r}
library(readr)
library(readxl)
library(stringr)



```


Descompresión de la carpeta

```{r}
ruta1 <- "data/entregas.zip"

entrega <- unzip("entregas.zip", exdir = "entregas")

```


Búsqueda de los archivos  mediante la función list.files.

Para los puntos buscamos patrones que contengan la palabra "puntos" y terminen en .txt

En el caso de los certificados buscamos documentos con extensión .pdf 

```{r}
ficheros_puntos <- list.files(path = "entregas", pattern = "\\.txt$", 
                              recursive = TRUE, full.names = TRUE)

ficheros_pdf <- list.files(path = "entregas", pattern = "\\.(pdf)$", 
                           recursive = TRUE, full.names = TRUE)



```





```{r}
library(tidyverse)
library(readxl)
vapellidos <- c()
vpuntos_num <- c()
vnom_file <- c()
vcontenido <- c()
vcarpetas_con_puntos <- c() # Para el análisis posterior

for (ruta in ficheros_puntos) {
  
  
  partes_ruta <- str_split(ruta, "/")[[1]]
  nombre_carpeta_alumno <- partes_ruta[length(partes_ruta) - 1]
  apellido <- str_split(nombre_carpeta_alumno, " ")[[1]][1]
  linea_texto <- readLines(ruta, n = 1, warn = FALSE)
  puntos_solo_num <- as.numeric(gsub("\\D", "", linea_texto))
  
  vapellidos <- c(vapellidos, apellido)
  vpuntos_num <- c(vpuntos_num, puntos_solo_num)
  vnom_file <- c(vnom_file, basename(ruta))
  vcontenido <- c(vcontenido, linea_texto)
  vcarpetas_con_puntos <- c(vcarpetas_con_puntos, dirname(ruta))
}


evalua_df <- data.frame(
  apellidos = vapellidos,
  puntos = vpuntos_num,
  NomFile = vnom_file,
  Puntos = vcontenido,
  stringsAsFactors = FALSE
)

#Ordenar por apellido 
evalua_df <- evalua_df %>% arrange(apellidos)
evalua_df

```

Respuestas a las preguntas 
```{r}
# ¿Todas las entregas usaron "puntos.txt"?
variantes_nombres <- unique(evalua_df$NomFile)
puntos_txt <- all(evalua_df$NomFile == "puntos.txt")

# ¿Cuántas variantes hay?
table(vnom_file)

# ¿Todas contienen el fichero de puntos y el justificante?

carpetas_puntos <- unique(dirname(ficheros_puntos))
carpetas_just <- unique(dirname(ficheros_pdf))
# Comparamos las carpetas que tienen puntos frente a las que tienen justificante
setdiff(carpetas_puntos, carpetas_just)
setdiff(carpetas_just, carpetas_puntos) 


```
Exportación de los resultados obtenidos

```{r}
library(openxlsx)
#Exportanción primer excel
write_xlsx(evalua_df, "NotasRIntermedio.xlsx")


ruta_al<- "data/AlumnosTD25_26.xlsx"
alumnos_matriculados <- read_excel(ruta_al)
colnames(alumnos_matriculados)[colnames(alumnos_matriculados) == "Apellido(s)"] <- "apellidos"

alumnos_notas <- merge(alumnos_matriculados, evalua_df, by = "apellidos", all.x = TRUE)

#Exportación segundo excel  
write_xlsx(alumnos_notas, "AlumnosNotas.xlsx")


```




